version: '3'

# set database password in .env
# please don't use quote (') or (") symbols in variables

services:
  icecast:
    image: jqtype/icecast
    container_name: icecast
    restart: unless-stopped
    volumes:
      - log:/var/log/icecast
    env_file: .env
    environment:
      - LETSENCRYPT_HOST=${ENV_LETSENCRYPT_HOST}
      - LETSENCRYPT_EMAIL=${ENV_LETSENCRYPT_EMAIL}
      - LETSENCRYPT_TEST=${ENV_LETSENCRYPT_TEST}
    expose:
      - "80"
    ports:
      - 58080:8080
    networks:
      proxy_front:

volumes:
  log:
    driver_opts:
      type: none
      device: $PWD/log
      o: bind

networks:
  proxy_front:
    external: true
